# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 200606


  data:
    redis:
      database: 0
      host: 121.43.228.48
      port: 6379
      timeout: 5000
      password: 654321
      lettuce:
        pool:
          max-active: 32
          max-wait: -1
          max-idle: 16
          min-idle: 8

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml